branches:
 only:
 - master
 - dev

language: python
python:
- 3.4
cache: pip

# scipy deps should be installed system-wide?
before_install:
- sudo apt-get build-dep python-scipy
install:
- pip install -r requirements.txt
- pip install dropbox

script:
- ./ci_runner.sh