branches:
 only:
 - master
 - dev

language: python
python:
- 3.4

# scipy deps should be installed system-wide?
before_install:
- sudo apt-get build-dep python-scipy
install:
- pip install -r requirements.txt
- pip install dropbox

script:
- python -m parse.ci_load_logs $dropbox_token local_dir
- python -m unittest discover
