branches:
 only:
 - master
 - dev
notifications:
  email: false
  
language: python
python:
- 3.4
cache: pip

# scipy deps should be installed system-wide?
before_install:
- sudo apt-get build-dep python-scipy
install:
- pip install -r requirements.txt
- pip install -I requests==2.14.0 # some bug in new requests ?
- pip install dropbox==7.1.0 # unknown import issues with newer version?

script:
- ./ci_runner.sh
